global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'example-app'
    static_configs:
      - targets: ['example-app:8080']
    metrics_path: /metrics
    scrape_interval: 5s

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']

  - job_name: 'isis-tracer-metrics'
    static_configs:
      - targets: ['example-app:8080']
    metrics_path: /tracer/metrics
    scrape_interval: 10s
    scrape_timeout: 5s
